### ISSUE TITLE
26223116: Mac OS X 10.11.4: AVURLAsset causes leak on AVCMNotificationDispatcher thread

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#14668]
#### Description

This thread (which contains none of my code, I can't even set a delegate to be called) autoreleases objects with no pool in place.
#0  0x00007fff93ee8723 in objc_autoreleaseNoPool ()
#1  0x00007fff93ed180b in (anonymous namespace)::AutoreleasePoolPage::autoreleaseNoPage(objc_object*) ()
#2  0x00007fff93ed50bf in objc_object::rootAutorelease2() ()
#3  0x00007fff9a91edd0 in __102-[AVCMNotificationDispatcher _addListenerAndCallback:forWeakReferenceToListener:callback:name:object:]_block_invoke ()
#4  0x00000001029ac070 in _dispatch_call_block_and_release ()
#5  0x000000010299ecc5 in _dispatch_client_callout ()
#6  0x00000001029a4112 in _dispatch_queue_drain ()
#7  0x00000001029abe24 in _dispatch_queue_invoke ()
#8  0x000000010299ecc5 in _dispatch_client_callout ()
#9  0x00000001029a3457 in _dispatch_root_queue_drain ()
#10 0x00000001029a28a5 in _dispatch_worker_thread3 ()
#11 0x0000000102a01336 in _pthread_wqthread ()
#12 0x00000001029fef91 in start_wqthread ()

Enqueued from com.apple.main-thread (Thread 1)Queue : com.apple.main-thread (serial)
#0  0x00000001029a1cb7 in _dispatch_barrier_async_f_slow ()
#1  0x00007fff9a83b490 in -[AVCMNotificationDispatcher _addListenerAndCallback:forWeakReferenceToListener:callback:name:object:]()
#2  0x00007fff9a83b337 in -[AVCMNotificationDispatcher addListenerWithWeakReference:callback:name:object:flags:]()
#3  0x00007fff9a89f0ec in -[AVAssetClientURLRequestHelper _startHandlingURLRequestsFromRequestOriginator:]()
#4  0x00007fff9a83b612 in -[AVURLAsset _setAssetInspectorLoader:]()
#5  0x00007fff9a83aa2f in -[AVURLAsset initWithURL:options:]()
#6  0x00007fff9a83a4cd in +[AVURLAsset URLAssetWithURL:options:]()
## 

Product Version: Mac OS X 10.11.4 (15E65)
Created: 2016-05-11T16:55:08.632840
Originated: 2016-05-11T18:54:00
Open Radar Link: http://www.openradar.me/26223116

**Comment by openradar-mirror** [comment]
Modified: 2016-05-11T16:55:08.633000
